### ISSUE TITLE
file paths

### ISSUE THREAD

**Issue by Halfbrowse** [ASD-at-GMF/disinfo-laundromat#20]
For non windows users there is an issue when trying to run crawler.py. 

Traceback (most recent call last):
  File "/disinfo-laundromat/crawler.py", line 807, in <module>
    input_data = pd.read_csv(args.input_file)
  File "/disinfo-laundromat/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/disinfo-laundromat/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/disinfo-laundromat/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/disinfo-laundromat/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/disinfo-laundromat/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/disinfo-laundromat/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/disinfo-laundromat/venv/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '.\\sites_of_concern.csv'

to fix this issue add the following to crawler.py 

```
import os

parser.add_argument(
    "-f",
    "--input-file",
    type=str,
    help="file containing list of domains",
    required=False,
    default=os.path.join(".", "sites_of_concern.csv"),
)
parser.add_argument(
    "-c", "--domain-column", type=str, required=False, default="Domain"
)
parser.add_argument(
    "-o",
    "--output-file",
    type=str,
    help="file to save final list of match results",
    required=False,
    default=os.path.join(".", "indicators_output.csv"),
)
```

this will allow all OS's to find the right path.

**Comment by pbenzoni** [comment]
Added a fix in the latest development commit, mind testing on a *nix enviroment for me?

https://github.com/ASD-at-GMF/disinfo-laundromat/tree/development

**Comment by Halfbrowse** [comment]
All good on my side now, thanks for the quick response!
